### ISSUE TITLE
Update clean-css on hosted website

### ISSUE THREAD

**Issue by pocketjoso** [AdamBurgess/clean-css-online#2]
Hi there, thanks for your tool, it's my go-to site for debugging clean-css issues.
However I noted that your hosted service (http://adam.id.au/clean-css-online/) seems to be running a quite old version of `clean-css` (looks like `3.1.x`) - could you please update to the latest?

Your package.json is fine; you just need to force install a later version (either `npm install clean-css@latest`, or just `rm -rf node_modules/clean-css && npm install`).

Keep up the good work!

**Comment by adamburgess** [comment]
will do

sorry for not responding, I saw this as you made it and then tried to update it using the new version of jspm, but that didn't work, so I guess I'll look at webpack
it'll get done, eventually

**Comment by adamburgess** [comment]
all done!

and in the process I knocked out 200kb due to using Preact instead of React 🌴 (I probably didn't need any framework, but hey, it's 7kb)
if I get some time in the future maybe I'll add some support for modification of clean-css options

>Hi there, thanks for your tool, it's my go-to site for debugging clean-css issues.

happy to be of service :)

**Comment by pocketjoso** [comment]
Awesome work!
