### ISSUE TITLE
Just simple question

### ISSUE THREAD

**Issue by ECAstack** [AdamBurgess/clean-css-online#4]
Why when I use the tool in the browser, in CSS code is removed
`` ../ `` 
in 
`` background: url (../ img / map.jpg) ``

**Comment by adamburgess** [comment]
clean-css will normalize/modify URLs, but I think when running it in a browser it might not work correctly.

I've disabled the normalisation and it should work now.

**Comment by ECAstack** [comment]
Thanks for support 😊
